### ISSUE TITLE
Error, no post data

### ISSUE THREAD

**Issue by saminpou** [CosmicSubspace/MSI-Keyboard-Lights#2]
POST unsuccessful. contents:
Page not found

---ERROR---
sha
Traceback (most recent call last):
  File "C:\Users\sha\Downloads\MSI-Keyboard-Lights-master\MSI-Keyboard-Lights-master\ScreenMirror.py", line 21, in <module>
    import MsiKeyboardLib as msi
  File "C:\Users\sha\Downloads\MSI-Keyboard-Lights-master\MSI-Keyboard-Lights-master\MsiKeyboardLib.py", line 224, in <module>
    game_register()
  File "C:\Users\sha\Downloads\MSI-Keyboard-Lights-master\MSI-Keyboard-Lights-master\MsiKeyboardLib.py", line 60, in game_register
    {"game":"FREEDRAW","golisp":"freedraw.lsp"})
  File "C:\Users\sha\Downloads\MSI-Keyboard-Lights-master\MSI-Keyboard-Lights-master\MsiKeyboardLib.py", line 52, in post
    raise
RuntimeError: No active exception to reraise

Press any key to exit.

**Comment by CosmicSubspace** [comment]
Thanks for the report!  
I _think_ the problem is in the url concatenation code, and is fixed in the latest commit. Re-download the repository and try running the script again.  
If you get an error (again), please post the console logs so I can try another fix.
